# Generated by Django 2.1.4 on 2019-01-04 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncrcrd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='show_breadcrumb',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='show_sidebar',
            field=models.BooleanField(default=True),
        ),
    ]
