# Generated by Django 2.1.4 on 2019-01-04 08:16

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('ncrcrd', '0002_auto_20190104_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('content', wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock()), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())])),
                ('show_sidebar', models.BooleanField(default=True)),
                ('show_breadcrumb', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '呼吸疾病中心页面模板/一般文章页',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='show_breadcrumb',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='show_sidebar',
            field=models.BooleanField(default=False),
        ),
    ]
