# Generated by Django 2.1.4 on 2019-01-07 07:20

from django.db import migrations, models
import django.db.models.deletion
import ncrcrd.blocks
import wagtail.contrib.table_block.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailimages', '0001_squashed_0021'),
        ('ncrcrd', '0003_auto_20190104_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseListPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('show_sidebar', models.BooleanField(default=False)),
                ('show_breadcrumb', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '呼吸疾病中心页面模板/科研培训文章列表页',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CoursePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('show_sidebar', models.BooleanField(default=False)),
                ('show_breadcrumb', models.BooleanField(default=False)),
                ('cover_title', models.TextField()),
                ('cover_introduction', models.TextField()),
                ('content', wagtail.core.fields.StreamField([('title', ncrcrd.blocks.TitleBlock()), ('heading', ncrcrd.blocks.HeadingBlock()), ('paragraph', ncrcrd.blocks.ParagraphBlock()), ('image', ncrcrd.blocks.ImageBlock()), ('person_card', wagtail.core.blocks.StructBlock([('picture', wagtail.images.blocks.ImageChooserBlock(label='照片')), ('name', wagtail.core.blocks.CharBlock(label='姓名')), ('description', wagtail.core.blocks.CharBlock(label='简介'))])), ('organization_card', wagtail.core.blocks.StructBlock([('picture', wagtail.images.blocks.ImageChooserBlock(label='Logo')), ('name', wagtail.core.blocks.CharBlock(label='名字')), ('description', wagtail.core.blocks.CharBlock(label='简介'))])), ('study_card', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(label='标题')), ('type', wagtail.core.blocks.CharBlock(label='项目类型')), ('leader', wagtail.core.blocks.CharBlock(label='负责人')), ('description', wagtail.core.blocks.CharBlock(label='项目简介')), ('status', wagtail.core.blocks.ChoiceBlock(choices=[('ongoing', '进行中'), ('finished', '已完成')], label='项目状态'))])), ('book_card', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(label='标题')), ('author', wagtail.core.blocks.CharBlock(label='作者')), ('description', wagtail.core.blocks.CharBlock(label='内容简介')), ('picture', wagtail.images.blocks.ImageChooserBlock(label='封面图片'))])), ('table', wagtail.contrib.table_block.blocks.TableBlock())])),
                ('cover_picture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ncrcrd_course_cover_pictures', to='wagtailimages.Image')),
            ],
            options={
                'verbose_name': '呼吸疾病中心页面模板/科研培训文章页',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NewsListPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('category_name', models.TextField()),
                ('show_sidebar', models.BooleanField(default=False)),
                ('show_breadcrumb', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '呼吸疾病中心页面模板/新闻列表页',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NewsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('show_sidebar', models.BooleanField(default=False)),
                ('show_breadcrumb', models.BooleanField(default=False)),
                ('category_name', models.TextField()),
                ('cover_title', models.TextField()),
                ('cover_introduction', models.TextField()),
                ('content', wagtail.core.fields.StreamField([('title', ncrcrd.blocks.TitleBlock()), ('heading', ncrcrd.blocks.HeadingBlock()), ('paragraph', ncrcrd.blocks.ParagraphBlock()), ('image', ncrcrd.blocks.ImageBlock()), ('person_card', wagtail.core.blocks.StructBlock([('picture', wagtail.images.blocks.ImageChooserBlock(label='照片')), ('name', wagtail.core.blocks.CharBlock(label='姓名')), ('description', wagtail.core.blocks.CharBlock(label='简介'))])), ('organization_card', wagtail.core.blocks.StructBlock([('picture', wagtail.images.blocks.ImageChooserBlock(label='Logo')), ('name', wagtail.core.blocks.CharBlock(label='名字')), ('description', wagtail.core.blocks.CharBlock(label='简介'))])), ('study_card', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(label='标题')), ('type', wagtail.core.blocks.CharBlock(label='项目类型')), ('leader', wagtail.core.blocks.CharBlock(label='负责人')), ('description', wagtail.core.blocks.CharBlock(label='项目简介')), ('status', wagtail.core.blocks.ChoiceBlock(choices=[('ongoing', '进行中'), ('finished', '已完成')], label='项目状态'))])), ('book_card', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(label='标题')), ('author', wagtail.core.blocks.CharBlock(label='作者')), ('description', wagtail.core.blocks.CharBlock(label='内容简介')), ('picture', wagtail.images.blocks.ImageChooserBlock(label='封面图片'))])), ('table', wagtail.contrib.table_block.blocks.TableBlock())])),
                ('cover_picture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ncrcrd_news_cover_pictures', to='wagtailimages.Image')),
            ],
            options={
                'verbose_name': '呼吸疾病中心页面模板/新闻页',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='content',
            field=wagtail.core.fields.StreamField([('title', ncrcrd.blocks.TitleBlock()), ('heading', ncrcrd.blocks.HeadingBlock()), ('paragraph', ncrcrd.blocks.ParagraphBlock()), ('image', ncrcrd.blocks.ImageBlock()), ('person_card', wagtail.core.blocks.StructBlock([('picture', wagtail.images.blocks.ImageChooserBlock(label='照片')), ('name', wagtail.core.blocks.CharBlock(label='姓名')), ('description', wagtail.core.blocks.CharBlock(label='简介'))])), ('organization_card', wagtail.core.blocks.StructBlock([('picture', wagtail.images.blocks.ImageChooserBlock(label='Logo')), ('name', wagtail.core.blocks.CharBlock(label='名字')), ('description', wagtail.core.blocks.CharBlock(label='简介'))])), ('study_card', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(label='标题')), ('type', wagtail.core.blocks.CharBlock(label='项目类型')), ('leader', wagtail.core.blocks.CharBlock(label='负责人')), ('description', wagtail.core.blocks.CharBlock(label='项目简介')), ('status', wagtail.core.blocks.ChoiceBlock(choices=[('ongoing', '进行中'), ('finished', '已完成')], label='项目状态'))])), ('book_card', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(label='标题')), ('author', wagtail.core.blocks.CharBlock(label='作者')), ('description', wagtail.core.blocks.CharBlock(label='内容简介')), ('picture', wagtail.images.blocks.ImageChooserBlock(label='封面图片'))])), ('table', wagtail.contrib.table_block.blocks.TableBlock())]),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.core.fields.StreamField([('title', wagtail.core.blocks.CharBlock(icon='snippet', label='文章标题')), ('paragraph', wagtail.core.blocks.RichTextBlock(label='文章段落'))]),
        ),
    ]
