# Generated by Django 2.1.4 on 2019-01-14 10:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import ncrcrd.blocks
import wagtail.contrib.table_block.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('ncrcrd', '0005_redirectpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='publish_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='这里控制的是显示出来的发布时间', verbose_name='发布时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='content',
            field=wagtail.core.fields.StreamField([('title', ncrcrd.blocks.TitleBlock()), ('heading', ncrcrd.blocks.HeadingBlock()), ('paragraph', ncrcrd.blocks.ParagraphBlock()), ('image', ncrcrd.blocks.ImageBlock()), ('person_card', wagtail.core.blocks.StructBlock([('picture', wagtail.images.blocks.ImageChooserBlock(label='照片')), ('name', wagtail.core.blocks.CharBlock(label='姓名')), ('description', wagtail.core.blocks.CharBlock(label='简介'))])), ('organization_card', wagtail.core.blocks.StructBlock([('picture', wagtail.images.blocks.ImageChooserBlock(label='Logo')), ('name', wagtail.core.blocks.CharBlock(label='名字')), ('description', wagtail.core.blocks.CharBlock(label='简介'))])), ('study_card', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(label='标题')), ('type', wagtail.core.blocks.CharBlock(label='项目类型')), ('leader', wagtail.core.blocks.CharBlock(label='负责人')), ('description', wagtail.core.blocks.CharBlock(label='项目简介')), ('status', wagtail.core.blocks.ChoiceBlock(choices=[('ongoing', '进行中'), ('finished', '已完成')], label='项目状态'))])), ('book_card', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(label='标题')), ('author', wagtail.core.blocks.CharBlock(label='作者')), ('description', wagtail.core.blocks.CharBlock(label='内容简介')), ('picture', wagtail.images.blocks.ImageChooserBlock(label='封面图片'))])), ('table', wagtail.contrib.table_block.blocks.TableBlock(label='表格'))], verbose_name='正文'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='show_breadcrumb',
            field=models.BooleanField(default=True, verbose_name='显示面包屑导航'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='show_sidebar',
            field=models.BooleanField(default=True, verbose_name='显示侧边栏'),
        ),
        migrations.AlterField(
            model_name='courselistpage',
            name='show_breadcrumb',
            field=models.BooleanField(default=True, verbose_name='显示面包屑导航'),
        ),
        migrations.AlterField(
            model_name='courselistpage',
            name='show_sidebar',
            field=models.BooleanField(default=True, verbose_name='显示侧边栏'),
        ),
        migrations.AlterField(
            model_name='coursepage',
            name='content',
            field=wagtail.core.fields.StreamField([('title', ncrcrd.blocks.TitleBlock()), ('heading', ncrcrd.blocks.HeadingBlock()), ('paragraph', ncrcrd.blocks.ParagraphBlock()), ('image', ncrcrd.blocks.ImageBlock()), ('person_card', wagtail.core.blocks.StructBlock([('picture', wagtail.images.blocks.ImageChooserBlock(label='照片')), ('name', wagtail.core.blocks.CharBlock(label='姓名')), ('description', wagtail.core.blocks.CharBlock(label='简介'))])), ('organization_card', wagtail.core.blocks.StructBlock([('picture', wagtail.images.blocks.ImageChooserBlock(label='Logo')), ('name', wagtail.core.blocks.CharBlock(label='名字')), ('description', wagtail.core.blocks.CharBlock(label='简介'))])), ('study_card', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(label='标题')), ('type', wagtail.core.blocks.CharBlock(label='项目类型')), ('leader', wagtail.core.blocks.CharBlock(label='负责人')), ('description', wagtail.core.blocks.CharBlock(label='项目简介')), ('status', wagtail.core.blocks.ChoiceBlock(choices=[('ongoing', '进行中'), ('finished', '已完成')], label='项目状态'))])), ('book_card', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(label='标题')), ('author', wagtail.core.blocks.CharBlock(label='作者')), ('description', wagtail.core.blocks.CharBlock(label='内容简介')), ('picture', wagtail.images.blocks.ImageChooserBlock(label='封面图片'))])), ('table', wagtail.contrib.table_block.blocks.TableBlock())], verbose_name='正文'),
        ),
        migrations.AlterField(
            model_name='coursepage',
            name='cover_introduction',
            field=models.TextField(verbose_name='封面介绍'),
        ),
        migrations.AlterField(
            model_name='coursepage',
            name='cover_picture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ncrcrd_course_cover_pictures', to='wagtailimages.Image', verbose_name='封面图片'),
        ),
        migrations.AlterField(
            model_name='coursepage',
            name='cover_title',
            field=models.TextField(verbose_name='封面标题'),
        ),
        migrations.AlterField(
            model_name='coursepage',
            name='show_breadcrumb',
            field=models.BooleanField(default=True, verbose_name='显示面包屑导航'),
        ),
        migrations.AlterField(
            model_name='coursepage',
            name='show_sidebar',
            field=models.BooleanField(default=True, verbose_name='显示侧边栏'),
        ),
        migrations.AlterField(
            model_name='newslistpage',
            name='category_name',
            field=models.TextField(choices=[('来访专家', '来访专家'), ('海外交流', '海外交流'), ('会议报导', '会议报导')], help_text='如需添加新的分类，请与开发沟通', verbose_name='文章分类'),
        ),
        migrations.AlterField(
            model_name='newslistpage',
            name='show_breadcrumb',
            field=models.BooleanField(default=True, verbose_name='显示面包屑导航'),
        ),
        migrations.AlterField(
            model_name='newslistpage',
            name='show_sidebar',
            field=models.BooleanField(default=True, verbose_name='显示侧边栏'),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='category_name',
            field=models.TextField(choices=[('来访专家', '来访专家'), ('海外交流', '海外交流'), ('会议报导', '会议报导')], help_text='如需添加新的分类，请与开发沟通', verbose_name='文章分类'),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='content',
            field=wagtail.core.fields.StreamField([('title', ncrcrd.blocks.TitleBlock()), ('heading', ncrcrd.blocks.HeadingBlock()), ('paragraph', ncrcrd.blocks.ParagraphBlock()), ('image', ncrcrd.blocks.ImageBlock()), ('person_card', wagtail.core.blocks.StructBlock([('picture', wagtail.images.blocks.ImageChooserBlock(label='照片')), ('name', wagtail.core.blocks.CharBlock(label='姓名')), ('description', wagtail.core.blocks.CharBlock(label='简介'))])), ('organization_card', wagtail.core.blocks.StructBlock([('picture', wagtail.images.blocks.ImageChooserBlock(label='Logo')), ('name', wagtail.core.blocks.CharBlock(label='名字')), ('description', wagtail.core.blocks.CharBlock(label='简介'))])), ('study_card', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(label='标题')), ('type', wagtail.core.blocks.CharBlock(label='项目类型')), ('leader', wagtail.core.blocks.CharBlock(label='负责人')), ('description', wagtail.core.blocks.CharBlock(label='项目简介')), ('status', wagtail.core.blocks.ChoiceBlock(choices=[('ongoing', '进行中'), ('finished', '已完成')], label='项目状态'))])), ('book_card', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(label='标题')), ('author', wagtail.core.blocks.CharBlock(label='作者')), ('description', wagtail.core.blocks.CharBlock(label='内容简介')), ('picture', wagtail.images.blocks.ImageChooserBlock(label='封面图片'))])), ('table', wagtail.contrib.table_block.blocks.TableBlock())], verbose_name='正文'),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='cover_introduction',
            field=models.TextField(verbose_name='封面介绍'),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='cover_picture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ncrcrd_news_cover_pictures', to='wagtailimages.Image', verbose_name='封面图片'),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='cover_title',
            field=models.TextField(verbose_name='封面标题'),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='show_breadcrumb',
            field=models.BooleanField(default=True, verbose_name='显示面包屑导航'),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='show_sidebar',
            field=models.BooleanField(default=True, verbose_name='显示侧边栏'),
        ),
        migrations.AlterField(
            model_name='redirectpage',
            name='redirect_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page', verbose_name='目标页面'),
        ),
    ]
