# Generated by Django 2.1.4 on 2019-01-15 01:59

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('ncrcrd', '0006_auto_20190114_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='carousel',
            field=wagtail.core.fields.StreamField([('carousel', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(label='标题')), ('picture', wagtail.images.blocks.ImageChooserBlock(label='图片')), ('page', wagtail.core.blocks.PageChooserBlock(label='文章'))]))], default='', verbose_name='轮播图配置'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='news',
            field=wagtail.core.fields.StreamField([('news', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(label='标题')), ('page', wagtail.core.blocks.PageChooserBlock(label='文章'))]))], default='', verbose_name='要闻动态配置'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.core.fields.StreamField([], blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='show_breadcrumb',
            field=models.BooleanField(default=False, verbose_name='显示面包屑导航'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='show_sidebar',
            field=models.BooleanField(default=False, verbose_name='显示侧边栏'),
        ),
    ]
