# Generated by Django 2.1.4 on 2019-01-16 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncrcrd', '0008_auto_20190116_0019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paperpage',
            name='content',
        ),
        migrations.RemoveField(
            model_name='paperpage',
            name='show_breadcrumb',
        ),
        migrations.RemoveField(
            model_name='paperpage',
            name='show_sidebar',
        ),
        migrations.AlterField(
            model_name='paperpage',
            name='authors',
            field=models.CharField(help_text='多位作者请用分隔符分割', max_length=255, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='paperpage',
            name='magazine',
            field=models.CharField(max_length=255, verbose_name='期刊名称'),
        ),
    ]
