# Generated by Django 2.1.4 on 2019-01-17 02:47

from django.db import migrations, models
import django.db.models.deletion
import ncrcrd.blocks
import wagtail.contrib.table_block.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('ncrcrd', '0009_auto_20190116_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='more_news_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='content',
            field=wagtail.core.fields.StreamField([('title', ncrcrd.blocks.TitleBlock()), ('heading', ncrcrd.blocks.HeadingBlock()), ('paragraph', ncrcrd.blocks.ParagraphBlock()), ('image', ncrcrd.blocks.ImageBlock()), ('person_card', wagtail.core.blocks.StructBlock([('picture', wagtail.images.blocks.ImageChooserBlock(label='照片')), ('name', wagtail.core.blocks.CharBlock(label='姓名')), ('description', wagtail.core.blocks.CharBlock(label='简介'))])), ('organization_card', wagtail.core.blocks.StructBlock([('picture', wagtail.images.blocks.ImageChooserBlock(label='Logo')), ('name', wagtail.core.blocks.CharBlock(label='名字')), ('description', wagtail.core.blocks.CharBlock(label='简介'))])), ('study_card', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(label='标题')), ('type', wagtail.core.blocks.CharBlock(label='项目类型')), ('leader', wagtail.core.blocks.CharBlock(label='负责人')), ('description', wagtail.core.blocks.CharBlock(label='项目简介')), ('page', wagtail.core.blocks.PageChooserBlock(label='内页链接', required=False)), ('status', wagtail.core.blocks.ChoiceBlock(choices=[('ongoing', '进行中'), ('finished', '已完成')], label='项目状态'))])), ('book_card', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(label='标题')), ('author', wagtail.core.blocks.CharBlock(label='作者')), ('description', wagtail.core.blocks.CharBlock(label='内容简介')), ('link', wagtail.core.blocks.URLBlock(label='外部链接', required=False)), ('picture', wagtail.images.blocks.ImageChooserBlock(label='封面图片'))])), ('table', wagtail.contrib.table_block.blocks.TableBlock(label='表格')), ('table_corporation', wagtail.contrib.table_block.blocks.TableBlock(label='协作单位表格', template='ncrcrd/blocks/table_corporation.html')), ('table_guide', wagtail.contrib.table_block.blocks.TableBlock(label='指南规范表格', template='ncrcrd/blocks/table_guide.html'))], verbose_name='正文'),
        ),
    ]
