# Generated by Django 2.1.4 on 2019-01-19 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncrcrd', '0010_auto_20190117_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='breadcrumb_title',
            field=models.TextField(blank=True, default='', help_text='不填时默认为页面标题', verbose_name='面包屑导航显示标题'),
        ),
        migrations.AddField(
            model_name='coursepage',
            name='breadcrumb_title',
            field=models.TextField(blank=True, default='', help_text='不填时默认为页面标题', verbose_name='面包屑导航显示标题'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='breadcrumb_title',
            field=models.TextField(blank=True, default='', help_text='不填时默认为页面标题', verbose_name='面包屑导航显示标题'),
        ),
        migrations.AddField(
            model_name='newspage',
            name='breadcrumb_title',
            field=models.TextField(blank=True, default='新闻详情', help_text='不填时默认为页面标题', verbose_name='面包屑导航显示标题'),
        ),
    ]
